version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5020:5020"
    environment:
      - DB_CONN=${DB_CONN:-sqlite:////app/data/pool.db}
      - PROXY_FETCHER_PATH=${PROXY_FETCHER_PATH:-/app/config/proxy_fetcher.json}
    volumes:
      - ./config/proxy_fetcher.json:/app/config/proxy_fetcher.json
      - ./data/pool.db:/app/data/pool.db
      - ./log:/app/log

