version: '2'
services:
  proxy_pool:
    build:
      context: .
      no_cache: true
    container_name: proxy_pool
    ports:
      - "5020:5020"
    environment:
      - DB_CONN=${DB_CONN:-sqlite:////app/data/pool.db}
      - PROXY_FETCHER_PATH=${PROXY_FETCHER_PATH:-/app/config/proxy_fetcher.json}
      - FETCH_THREAD_NUM=${FETCH_THREAD_NUM:-30}
      - FETCH_WORKER_NUM=${FETCH_WORKER_NUM:-30}
      - CHECK_THREAD_NUM=${CHECK_THREAD_NUM:-20}
      - CHECK_WORKER_NUM=${CHECK_WORKER_NUM:-20}
      - JOB_MAX_INSTANCES=${JOB_MAX_INSTANCES:-10}
      - JOB_COALESCE=${JOB_COALESCE:-False}
    volumes:
      - ./config/proxy_fetcher.json:/app/config/proxy_fetcher.json
      - ./data/pool.db:/app/data/pool.db
      - ./log:/app/log

